baseURL = 'https://frosty-einstein-e2560f.netlify.app/'
languageCode = 'en-us'
title = 'American Journal of Health Studies'
theme = "hugo-highlights-theme"

[params]

    # Redirect to another site after 5 seconds
    redirectURL = "https://www.amjhealthstudies.com/index.php/ajhs/"
    redirectDelay = 5
    # Use these for testing.
    #redirectURL = ""
    #redirectDelay = 1500

    # To provide more meta data for search engings feel free to add a few informations.
    # This lines will be inserted as meta tags.
    name = "Your Name"
    description = "Your Description"
    image = ""

    # If this param is set to true, every section gets an own background image (located at static/images)
    # to change the image you could use the param picture on every section.
    # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
    backgroundpersection = true

    # hero Section
    [params.hero]
        type = "hero"
        title = "American Journal of Health Studies"
        description = "We upgraded our system. Please update your bookmarks. You will be redirected soon..."
        buttontext = "begin"

    [params.footer]
        enable = true
